require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AttagsController do

  # This should return the minimal set of attributes required to create a valid
  # Attag. As you add validations to Attag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AttagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all attags as @attags" do
      attag = Attag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:attags).should eq([attag])
    end
  end

  describe "GET show" do
    it "assigns the requested attag as @attag" do
      attag = Attag.create! valid_attributes
      get :show, {:id => attag.to_param}, valid_session
      assigns(:attag).should eq(attag)
    end
  end

  describe "GET new" do
    it "assigns a new attag as @attag" do
      get :new, {}, valid_session
      assigns(:attag).should be_a_new(Attag)
    end
  end

  describe "GET edit" do
    it "assigns the requested attag as @attag" do
      attag = Attag.create! valid_attributes
      get :edit, {:id => attag.to_param}, valid_session
      assigns(:attag).should eq(attag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Attag" do
        expect {
          post :create, {:attag => valid_attributes}, valid_session
        }.to change(Attag, :count).by(1)
      end

      it "assigns a newly created attag as @attag" do
        post :create, {:attag => valid_attributes}, valid_session
        assigns(:attag).should be_a(Attag)
        assigns(:attag).should be_persisted
      end

      it "redirects to the created attag" do
        post :create, {:attag => valid_attributes}, valid_session
        response.should redirect_to(Attag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved attag as @attag" do
        # Trigger the behavior that occurs when invalid params are submitted
        Attag.any_instance.stub(:save).and_return(false)
        post :create, {:attag => {  }}, valid_session
        assigns(:attag).should be_a_new(Attag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Attag.any_instance.stub(:save).and_return(false)
        post :create, {:attag => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested attag" do
        attag = Attag.create! valid_attributes
        # Assuming there are no other attags in the database, this
        # specifies that the Attag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Attag.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => attag.to_param, :attag => { "these" => "params" }}, valid_session
      end

      it "assigns the requested attag as @attag" do
        attag = Attag.create! valid_attributes
        put :update, {:id => attag.to_param, :attag => valid_attributes}, valid_session
        assigns(:attag).should eq(attag)
      end

      it "redirects to the attag" do
        attag = Attag.create! valid_attributes
        put :update, {:id => attag.to_param, :attag => valid_attributes}, valid_session
        response.should redirect_to(attag)
      end
    end

    describe "with invalid params" do
      it "assigns the attag as @attag" do
        attag = Attag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Attag.any_instance.stub(:save).and_return(false)
        put :update, {:id => attag.to_param, :attag => {  }}, valid_session
        assigns(:attag).should eq(attag)
      end

      it "re-renders the 'edit' template" do
        attag = Attag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Attag.any_instance.stub(:save).and_return(false)
        put :update, {:id => attag.to_param, :attag => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested attag" do
      attag = Attag.create! valid_attributes
      expect {
        delete :destroy, {:id => attag.to_param}, valid_session
      }.to change(Attag, :count).by(-1)
    end

    it "redirects to the attags list" do
      attag = Attag.create! valid_attributes
      delete :destroy, {:id => attag.to_param}, valid_session
      response.should redirect_to(attags_url)
    end
  end

end
